# Generated by Django 5.2.2 on 2025-06-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
